# Generated by Django 6.0.1 on 2026-01-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0004_userprofile_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="Tasks_notif_user_id_2be244_idx",
            old_name="Tasks_notif_user_id_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="Tasks_notif_user_id_ce77ce_idx",
            old_name="Tasks_notif_user_id_created_idx",
        ),
    ]
